// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct MissionDataMsg {
  var inAppMissionId: String? = nil
  var progressCode: String? = nil
  var title: String? = nil
  var details: String? = nil
  var point: Int64? = nil
  var targetProgress: Int64? = nil
  var currentProgress: Int64? = nil
  var hasAchievement: Bool? = nil
  var isClaimed: Bool? = nil
  var displayOrder: Int64? = nil
  var cycleType: Int64? = nil
  var rewardType: Int64? = nil
  var rewardItemCode: String? = nil
  var rewardItemQuantity: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MissionDataMsg? {
    let inAppMissionId: String? = nilOrValue(pigeonVar_list[0])
    let progressCode: String? = nilOrValue(pigeonVar_list[1])
    let title: String? = nilOrValue(pigeonVar_list[2])
    let details: String? = nilOrValue(pigeonVar_list[3])
    let point: Int64? = nilOrValue(pigeonVar_list[4])
    let targetProgress: Int64? = nilOrValue(pigeonVar_list[5])
    let currentProgress: Int64? = nilOrValue(pigeonVar_list[6])
    let hasAchievement: Bool? = nilOrValue(pigeonVar_list[7])
    let isClaimed: Bool? = nilOrValue(pigeonVar_list[8])
    let displayOrder: Int64? = nilOrValue(pigeonVar_list[9])
    let cycleType: Int64? = nilOrValue(pigeonVar_list[10])
    let rewardType: Int64? = nilOrValue(pigeonVar_list[11])
    let rewardItemCode: String? = nilOrValue(pigeonVar_list[12])
    let rewardItemQuantity: Int64? = nilOrValue(pigeonVar_list[13])

    return MissionDataMsg(
      inAppMissionId: inAppMissionId,
      progressCode: progressCode,
      title: title,
      details: details,
      point: point,
      targetProgress: targetProgress,
      currentProgress: currentProgress,
      hasAchievement: hasAchievement,
      isClaimed: isClaimed,
      displayOrder: displayOrder,
      cycleType: cycleType,
      rewardType: rewardType,
      rewardItemCode: rewardItemCode,
      rewardItemQuantity: rewardItemQuantity
    )
  }
  func toList() -> [Any?] {
    return [
      inAppMissionId,
      progressCode,
      title,
      details,
      point,
      targetProgress,
      currentProgress,
      hasAchievement,
      isClaimed,
      displayOrder,
      cycleType,
      rewardType,
      rewardItemCode,
      rewardItemQuantity,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MissionListFilterMsg {
  var cycleType: Int64? = nil
  var rewardType: Int64? = nil
  var progressCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MissionListFilterMsg? {
    let cycleType: Int64? = nilOrValue(pigeonVar_list[0])
    let rewardType: Int64? = nilOrValue(pigeonVar_list[1])
    let progressCode: String? = nilOrValue(pigeonVar_list[2])

    return MissionListFilterMsg(
      cycleType: cycleType,
      rewardType: rewardType,
      progressCode: progressCode
    )
  }
  func toList() -> [Any?] {
    return [
      cycleType,
      rewardType,
      progressCode,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WebPortalOptionsMsg {
  var handle: Int64? = nil
  var volume: Double? = nil
  var showMode: Int64? = nil
  var embeddedX: Int64? = nil
  var embeddedY: Int64? = nil
  var embeddedWidth: Int64? = nil
  var embeddedHeight: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WebPortalOptionsMsg? {
    let handle: Int64? = nilOrValue(pigeonVar_list[0])
    let volume: Double? = nilOrValue(pigeonVar_list[1])
    let showMode: Int64? = nilOrValue(pigeonVar_list[2])
    let embeddedX: Int64? = nilOrValue(pigeonVar_list[3])
    let embeddedY: Int64? = nilOrValue(pigeonVar_list[4])
    let embeddedWidth: Int64? = nilOrValue(pigeonVar_list[5])
    let embeddedHeight: Int64? = nilOrValue(pigeonVar_list[6])

    return WebPortalOptionsMsg(
      handle: handle,
      volume: volume,
      showMode: showMode,
      embeddedX: embeddedX,
      embeddedY: embeddedY,
      embeddedWidth: embeddedWidth,
      embeddedHeight: embeddedHeight
    )
  }
  func toList() -> [Any?] {
    return [
      handle,
      volume,
      showMode,
      embeddedX,
      embeddedY,
      embeddedWidth,
      embeddedHeight,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PendingItemGrantMsg {
  var grantId: String? = nil
  var itemCode: String? = nil
  var quantity: Int64? = nil
  var grantedAtUnixMs: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PendingItemGrantMsg? {
    let grantId: String? = nilOrValue(pigeonVar_list[0])
    let itemCode: String? = nilOrValue(pigeonVar_list[1])
    let quantity: Int64? = nilOrValue(pigeonVar_list[2])
    let grantedAtUnixMs: Int64? = nilOrValue(pigeonVar_list[3])

    return PendingItemGrantMsg(
      grantId: grantId,
      itemCode: itemCode,
      quantity: quantity,
      grantedAtUnixMs: grantedAtUnixMs
    )
  }
  func toList() -> [Any?] {
    return [
      grantId,
      itemCode,
      quantity,
      grantedAtUnixMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SyncItemGrantsResultMsg {
  var totalSynced: Int64? = nil
  var totalMarked: Int64? = nil
  var pageCount: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SyncItemGrantsResultMsg? {
    let totalSynced: Int64? = nilOrValue(pigeonVar_list[0])
    let totalMarked: Int64? = nilOrValue(pigeonVar_list[1])
    let pageCount: Int64? = nilOrValue(pigeonVar_list[2])

    return SyncItemGrantsResultMsg(
      totalSynced: totalSynced,
      totalMarked: totalMarked,
      pageCount: pageCount
    )
  }
  func toList() -> [Any?] {
    return [
      totalSynced,
      totalMarked,
      pageCount,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MissionDataMsg.fromList(self.readValue() as! [Any?])
    case 130:
      return MissionListFilterMsg.fromList(self.readValue() as! [Any?])
    case 131:
      return WebPortalOptionsMsg.fromList(self.readValue() as! [Any?])
    case 132:
      return PendingItemGrantMsg.fromList(self.readValue() as! [Any?])
    case 133:
      return SyncItemGrantsResultMsg.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MissionDataMsg {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? MissionListFilterMsg {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? WebPortalOptionsMsg {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PendingItemGrantMsg {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? SyncItemGrantsResultMsg {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PoilinkHostApi {
  func setConfig(clientId: String, clientSecret: String) throws
  func initialize(completion: @escaping (Result<Void, Error>) -> Void)
  func authenticate(appUserId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func unauthenticate() throws
  func getRefreshToken(completion: @escaping (Result<String, Error>) -> Void)
  func setRefreshToken(appUserId: String, refreshToken: String, completion: @escaping (Result<Void, Error>) -> Void)
  func progressMission(handle: Int64, missionCode: String, amount: Int64, mode: Int64) throws
  func progressMissionImmediate(missionCode: String, amount: Int64, mode: Int64, idempotencyKey: String?, completion: @escaping (Result<[MissionDataMsg], Error>) -> Void)
  func getMissionList(filter: MissionListFilterMsg?, completion: @escaping (Result<[MissionDataMsg], Error>) -> Void)
  func showWebPortal(options: WebPortalOptionsMsg) throws
  func preloadWebPortal(options: WebPortalOptionsMsg) throws
  func closeWebPortal() throws
  func syncItemGrants(handle: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PoilinkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `PoilinkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PoilinkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setConfigChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setConfig\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setConfigChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let clientIdArg = args[0] as! String
        let clientSecretArg = args[1] as! String
        do {
          try api.setConfig(clientId: clientIdArg, clientSecret: clientSecretArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setConfigChannel.setMessageHandler(nil)
    }
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { _, reply in
        api.initialize { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appUserIdArg = args[0] as! String
        api.authenticate(appUserId: appUserIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
    let unauthenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.unauthenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unauthenticateChannel.setMessageHandler { _, reply in
        do {
          try api.unauthenticate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unauthenticateChannel.setMessageHandler(nil)
    }
    let getRefreshTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getRefreshToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRefreshTokenChannel.setMessageHandler { _, reply in
        api.getRefreshToken { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getRefreshTokenChannel.setMessageHandler(nil)
    }
    let setRefreshTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setRefreshToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setRefreshTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appUserIdArg = args[0] as! String
        let refreshTokenArg = args[1] as! String
        api.setRefreshToken(appUserId: appUserIdArg, refreshToken: refreshTokenArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setRefreshTokenChannel.setMessageHandler(nil)
    }
    let progressMissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      progressMissionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        let missionCodeArg = args[1] as! String
        let amountArg = args[2] as! Int64
        let modeArg = args[3] as! Int64
        do {
          try api.progressMission(handle: handleArg, missionCode: missionCodeArg, amount: amountArg, mode: modeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      progressMissionChannel.setMessageHandler(nil)
    }
    let progressMissionImmediateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMissionImmediate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      progressMissionImmediateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let missionCodeArg = args[0] as! String
        let amountArg = args[1] as! Int64
        let modeArg = args[2] as! Int64
        let idempotencyKeyArg: String? = nilOrValue(args[3])
        api.progressMissionImmediate(missionCode: missionCodeArg, amount: amountArg, mode: modeArg, idempotencyKey: idempotencyKeyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      progressMissionImmediateChannel.setMessageHandler(nil)
    }
    let getMissionListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getMissionList\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMissionListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filterArg: MissionListFilterMsg? = nilOrValue(args[0])
        api.getMissionList(filter: filterArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMissionListChannel.setMessageHandler(nil)
    }
    let showWebPortalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.showWebPortal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showWebPortalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! WebPortalOptionsMsg
        do {
          try api.showWebPortal(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showWebPortalChannel.setMessageHandler(nil)
    }
    let preloadWebPortalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.preloadWebPortal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      preloadWebPortalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! WebPortalOptionsMsg
        do {
          try api.preloadWebPortal(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      preloadWebPortalChannel.setMessageHandler(nil)
    }
    let closeWebPortalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.closeWebPortal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeWebPortalChannel.setMessageHandler { _, reply in
        do {
          try api.closeWebPortal()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      closeWebPortalChannel.setMessageHandler(nil)
    }
    let syncItemGrantsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.syncItemGrants\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncItemGrantsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let handleArg = args[0] as! Int64
        do {
          try api.syncItemGrants(handle: handleArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      syncItemGrantsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PoilinkEventApiProtocol {
  func onWebPortalShown(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWebPortalClose(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWebPortalError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMissionChallenge(handle handleArg: Int64, missionId missionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onRewardReceive(handle handleArg: Int64, grantId grantIdArg: String, itemCode itemCodeArg: String, quantity quantityArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onProgressMissionError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onGrantsPage(handle handleArg: Int64, grants grantsArg: [PendingItemGrantMsg], completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncComplete(handle handleArg: Int64, result resultArg: SyncItemGrantsResultMsg, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onSyncError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class PoilinkEventApi: PoilinkEventApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onWebPortalShown(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalShown\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onWebPortalClose(handle handleArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalClose\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onWebPortalError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, errorCodeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onMissionChallenge(handle handleArg: Int64, missionId missionIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, missionIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onRewardReceive(handle handleArg: Int64, grantId grantIdArg: String, itemCode itemCodeArg: String, quantity quantityArg: Int64, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, grantIdArg, itemCodeArg, quantityArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onProgressMissionError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, errorCodeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onGrantsPage(handle handleArg: Int64, grants grantsArg: [PendingItemGrantMsg], completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, grantsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncComplete(handle handleArg: Int64, result resultArg: SyncItemGrantsResultMsg, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, resultArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onSyncError(handle handleArg: Int64, errorCode errorCodeArg: Int64, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([handleArg, errorCodeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
