// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

class MissionDataMsg {
  MissionDataMsg({
    this.inAppMissionId,
    this.progressCode,
    this.title,
    this.details,
    this.point,
    this.targetProgress,
    this.currentProgress,
    this.hasAchievement,
    this.isClaimed,
    this.displayOrder,
    this.cycleType,
    this.rewardType,
    this.rewardItemCode,
    this.rewardItemQuantity,
  });

  String? inAppMissionId;

  String? progressCode;

  String? title;

  String? details;

  int? point;

  int? targetProgress;

  int? currentProgress;

  bool? hasAchievement;

  bool? isClaimed;

  int? displayOrder;

  int? cycleType;

  int? rewardType;

  String? rewardItemCode;

  int? rewardItemQuantity;

  Object encode() {
    return <Object?>[
      inAppMissionId,
      progressCode,
      title,
      details,
      point,
      targetProgress,
      currentProgress,
      hasAchievement,
      isClaimed,
      displayOrder,
      cycleType,
      rewardType,
      rewardItemCode,
      rewardItemQuantity,
    ];
  }

  static MissionDataMsg decode(Object result) {
    result as List<Object?>;
    return MissionDataMsg(
      inAppMissionId: result[0] as String?,
      progressCode: result[1] as String?,
      title: result[2] as String?,
      details: result[3] as String?,
      point: result[4] as int?,
      targetProgress: result[5] as int?,
      currentProgress: result[6] as int?,
      hasAchievement: result[7] as bool?,
      isClaimed: result[8] as bool?,
      displayOrder: result[9] as int?,
      cycleType: result[10] as int?,
      rewardType: result[11] as int?,
      rewardItemCode: result[12] as String?,
      rewardItemQuantity: result[13] as int?,
    );
  }
}

class MissionListFilterMsg {
  MissionListFilterMsg({
    this.cycleType,
    this.rewardType,
    this.progressCode,
  });

  int? cycleType;

  int? rewardType;

  String? progressCode;

  Object encode() {
    return <Object?>[
      cycleType,
      rewardType,
      progressCode,
    ];
  }

  static MissionListFilterMsg decode(Object result) {
    result as List<Object?>;
    return MissionListFilterMsg(
      cycleType: result[0] as int?,
      rewardType: result[1] as int?,
      progressCode: result[2] as String?,
    );
  }
}

class WebPortalOptionsMsg {
  WebPortalOptionsMsg({
    this.handle,
    this.volume,
    this.showMode,
    this.embeddedX,
    this.embeddedY,
    this.embeddedWidth,
    this.embeddedHeight,
  });

  int? handle;

  double? volume;

  int? showMode;

  int? embeddedX;

  int? embeddedY;

  int? embeddedWidth;

  int? embeddedHeight;

  Object encode() {
    return <Object?>[
      handle,
      volume,
      showMode,
      embeddedX,
      embeddedY,
      embeddedWidth,
      embeddedHeight,
    ];
  }

  static WebPortalOptionsMsg decode(Object result) {
    result as List<Object?>;
    return WebPortalOptionsMsg(
      handle: result[0] as int?,
      volume: result[1] as double?,
      showMode: result[2] as int?,
      embeddedX: result[3] as int?,
      embeddedY: result[4] as int?,
      embeddedWidth: result[5] as int?,
      embeddedHeight: result[6] as int?,
    );
  }
}

class PendingItemGrantMsg {
  PendingItemGrantMsg({
    this.grantId,
    this.itemCode,
    this.quantity,
    this.grantedAtUnixMs,
  });

  String? grantId;

  String? itemCode;

  int? quantity;

  int? grantedAtUnixMs;

  Object encode() {
    return <Object?>[
      grantId,
      itemCode,
      quantity,
      grantedAtUnixMs,
    ];
  }

  static PendingItemGrantMsg decode(Object result) {
    result as List<Object?>;
    return PendingItemGrantMsg(
      grantId: result[0] as String?,
      itemCode: result[1] as String?,
      quantity: result[2] as int?,
      grantedAtUnixMs: result[3] as int?,
    );
  }
}

class SyncItemGrantsResultMsg {
  SyncItemGrantsResultMsg({
    this.totalSynced,
    this.totalMarked,
    this.pageCount,
  });

  int? totalSynced;

  int? totalMarked;

  int? pageCount;

  Object encode() {
    return <Object?>[
      totalSynced,
      totalMarked,
      pageCount,
    ];
  }

  static SyncItemGrantsResultMsg decode(Object result) {
    result as List<Object?>;
    return SyncItemGrantsResultMsg(
      totalSynced: result[0] as int?,
      totalMarked: result[1] as int?,
      pageCount: result[2] as int?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MissionDataMsg) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is MissionListFilterMsg) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is WebPortalOptionsMsg) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is PendingItemGrantMsg) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is SyncItemGrantsResultMsg) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return MissionDataMsg.decode(readValue(buffer)!);
      case 130: 
        return MissionListFilterMsg.decode(readValue(buffer)!);
      case 131: 
        return WebPortalOptionsMsg.decode(readValue(buffer)!);
      case 132: 
        return PendingItemGrantMsg.decode(readValue(buffer)!);
      case 133: 
        return SyncItemGrantsResultMsg.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class PoilinkHostApi {
  /// Constructor for [PoilinkHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PoilinkHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setConfig(String clientId, String clientSecret) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setConfig$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[clientId, clientSecret]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> initialize() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> authenticate(String appUserId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.authenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[appUserId]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> unauthenticate() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.unauthenticate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getRefreshToken() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getRefreshToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<void> setRefreshToken(String appUserId, String refreshToken) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setRefreshToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[appUserId, refreshToken]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> progressMission(int handle, String missionCode, int amount, int mode) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle, missionCode, amount, mode]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<MissionDataMsg>> progressMissionImmediate(String missionCode, int amount, int mode, String? idempotencyKey) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMissionImmediate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[missionCode, amount, mode, idempotencyKey]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MissionDataMsg>();
    }
  }

  Future<List<MissionDataMsg>> getMissionList(MissionListFilterMsg? filter) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getMissionList$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filter]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<MissionDataMsg>();
    }
  }

  Future<void> showWebPortal(WebPortalOptionsMsg options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.showWebPortal$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> preloadWebPortal(WebPortalOptionsMsg options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.preloadWebPortal$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeWebPortal() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.closeWebPortal$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> syncItemGrants(int handle) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.syncItemGrants$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[handle]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class PoilinkEventApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onWebPortalShown(int handle);

  void onWebPortalClose(int handle);

  void onWebPortalError(int handle, int errorCode, String message);

  void onMissionChallenge(int handle, String missionId);

  void onRewardReceive(int handle, String grantId, String itemCode, int quantity, String missionCode);

  void onProgressMissionError(int handle, int errorCode, String message);

  void onGrantsPage(int handle, List<PendingItemGrantMsg> grants);

  void onSyncComplete(int handle, SyncItemGrantsResultMsg result);

  void onSyncError(int handle, int errorCode, String message);

  static void setUp(PoilinkEventApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalShown$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalShown was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalShown was null, expected non-null int.');
          try {
            api.onWebPortalShown(arg_handle!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalClose$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalClose was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalClose was null, expected non-null int.');
          try {
            api.onWebPortalClose(arg_handle!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError was null, expected non-null int.');
          final int? arg_errorCode = (args[1] as int?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError was null, expected non-null int.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError was null, expected non-null String.');
          try {
            api.onWebPortalError(arg_handle!, arg_errorCode!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge was null, expected non-null int.');
          final String? arg_missionId = (args[1] as String?);
          assert(arg_missionId != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge was null, expected non-null String.');
          try {
            api.onMissionChallenge(arg_handle!, arg_missionId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null, expected non-null int.');
          final String? arg_grantId = (args[1] as String?);
          assert(arg_grantId != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null, expected non-null String.');
          final String? arg_itemCode = (args[2] as String?);
          assert(arg_itemCode != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null, expected non-null String.');
          final int? arg_quantity = (args[3] as int?);
          assert(arg_quantity != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null, expected non-null int.');
          final String? arg_missionCode = (args[4] as String?);
          assert(arg_missionCode != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive was null, expected non-null String.');
          try {
            api.onRewardReceive(arg_handle!, arg_grantId!, arg_itemCode!, arg_quantity!, arg_missionCode!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError was null, expected non-null int.');
          final int? arg_errorCode = (args[1] as int?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError was null, expected non-null int.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError was null, expected non-null String.');
          try {
            api.onProgressMissionError(arg_handle!, arg_errorCode!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage was null, expected non-null int.');
          final List<PendingItemGrantMsg>? arg_grants = (args[1] as List<Object?>?)?.cast<PendingItemGrantMsg>();
          assert(arg_grants != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage was null, expected non-null List<PendingItemGrantMsg>.');
          try {
            api.onGrantsPage(arg_handle!, arg_grants!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete was null, expected non-null int.');
          final SyncItemGrantsResultMsg? arg_result = (args[1] as SyncItemGrantsResultMsg?);
          assert(arg_result != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete was null, expected non-null SyncItemGrantsResultMsg.');
          try {
            api.onSyncComplete(arg_handle!, arg_result!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final int? arg_handle = (args[0] as int?);
          assert(arg_handle != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError was null, expected non-null int.');
          final int? arg_errorCode = (args[1] as int?);
          assert(arg_errorCode != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError was null, expected non-null int.');
          final String? arg_message = (args[2] as String?);
          assert(arg_message != null,
              'Argument for dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError was null, expected non-null String.');
          try {
            api.onSyncError(arg_handle!, arg_errorCode!, arg_message!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
