// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.poilink.sdk.flutter

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class MissionDataMsg (
  val inAppMissionId: String? = null,
  val progressCode: String? = null,
  val title: String? = null,
  val details: String? = null,
  val point: Long? = null,
  val targetProgress: Long? = null,
  val currentProgress: Long? = null,
  val hasAchievement: Boolean? = null,
  val isClaimed: Boolean? = null,
  val displayOrder: Long? = null,
  val cycleType: Long? = null,
  val rewardType: Long? = null,
  val rewardItemCode: String? = null,
  val rewardItemQuantity: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MissionDataMsg {
      val inAppMissionId = pigeonVar_list[0] as String?
      val progressCode = pigeonVar_list[1] as String?
      val title = pigeonVar_list[2] as String?
      val details = pigeonVar_list[3] as String?
      val point = pigeonVar_list[4] as Long?
      val targetProgress = pigeonVar_list[5] as Long?
      val currentProgress = pigeonVar_list[6] as Long?
      val hasAchievement = pigeonVar_list[7] as Boolean?
      val isClaimed = pigeonVar_list[8] as Boolean?
      val displayOrder = pigeonVar_list[9] as Long?
      val cycleType = pigeonVar_list[10] as Long?
      val rewardType = pigeonVar_list[11] as Long?
      val rewardItemCode = pigeonVar_list[12] as String?
      val rewardItemQuantity = pigeonVar_list[13] as Long?
      return MissionDataMsg(inAppMissionId, progressCode, title, details, point, targetProgress, currentProgress, hasAchievement, isClaimed, displayOrder, cycleType, rewardType, rewardItemCode, rewardItemQuantity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      inAppMissionId,
      progressCode,
      title,
      details,
      point,
      targetProgress,
      currentProgress,
      hasAchievement,
      isClaimed,
      displayOrder,
      cycleType,
      rewardType,
      rewardItemCode,
      rewardItemQuantity,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MissionListFilterMsg (
  val cycleType: Long? = null,
  val rewardType: Long? = null,
  val progressCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MissionListFilterMsg {
      val cycleType = pigeonVar_list[0] as Long?
      val rewardType = pigeonVar_list[1] as Long?
      val progressCode = pigeonVar_list[2] as String?
      return MissionListFilterMsg(cycleType, rewardType, progressCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      cycleType,
      rewardType,
      progressCode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WebPortalOptionsMsg (
  val handle: Long? = null,
  val volume: Double? = null,
  val showMode: Long? = null,
  val embeddedX: Long? = null,
  val embeddedY: Long? = null,
  val embeddedWidth: Long? = null,
  val embeddedHeight: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WebPortalOptionsMsg {
      val handle = pigeonVar_list[0] as Long?
      val volume = pigeonVar_list[1] as Double?
      val showMode = pigeonVar_list[2] as Long?
      val embeddedX = pigeonVar_list[3] as Long?
      val embeddedY = pigeonVar_list[4] as Long?
      val embeddedWidth = pigeonVar_list[5] as Long?
      val embeddedHeight = pigeonVar_list[6] as Long?
      return WebPortalOptionsMsg(handle, volume, showMode, embeddedX, embeddedY, embeddedWidth, embeddedHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      handle,
      volume,
      showMode,
      embeddedX,
      embeddedY,
      embeddedWidth,
      embeddedHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PendingItemGrantMsg (
  val grantId: String? = null,
  val itemCode: String? = null,
  val quantity: Long? = null,
  val grantedAtUnixMs: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PendingItemGrantMsg {
      val grantId = pigeonVar_list[0] as String?
      val itemCode = pigeonVar_list[1] as String?
      val quantity = pigeonVar_list[2] as Long?
      val grantedAtUnixMs = pigeonVar_list[3] as Long?
      return PendingItemGrantMsg(grantId, itemCode, quantity, grantedAtUnixMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      grantId,
      itemCode,
      quantity,
      grantedAtUnixMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SyncItemGrantsResultMsg (
  val totalSynced: Long? = null,
  val totalMarked: Long? = null,
  val pageCount: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SyncItemGrantsResultMsg {
      val totalSynced = pigeonVar_list[0] as Long?
      val totalMarked = pigeonVar_list[1] as Long?
      val pageCount = pigeonVar_list[2] as Long?
      return SyncItemGrantsResultMsg(totalSynced, totalMarked, pageCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalSynced,
      totalMarked,
      pageCount,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MissionDataMsg.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MissionListFilterMsg.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WebPortalOptionsMsg.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PendingItemGrantMsg.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SyncItemGrantsResultMsg.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MissionDataMsg -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is MissionListFilterMsg -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is WebPortalOptionsMsg -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PendingItemGrantMsg -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SyncItemGrantsResultMsg -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PoilinkHostApi {
  fun setConfig(clientId: String, clientSecret: String)
  fun initialize(callback: (Result<Unit>) -> Unit)
  fun authenticate(appUserId: String, callback: (Result<Unit>) -> Unit)
  fun unauthenticate()
  fun getRefreshToken(callback: (Result<String>) -> Unit)
  fun setRefreshToken(appUserId: String, refreshToken: String, callback: (Result<Unit>) -> Unit)
  fun progressMission(handle: Long, missionCode: String, amount: Long, mode: Long)
  fun progressMissionImmediate(missionCode: String, amount: Long, mode: Long, idempotencyKey: String?, callback: (Result<List<MissionDataMsg>>) -> Unit)
  fun getMissionList(filter: MissionListFilterMsg?, callback: (Result<List<MissionDataMsg>>) -> Unit)
  fun showWebPortal(options: WebPortalOptionsMsg)
  fun preloadWebPortal(options: WebPortalOptionsMsg)
  fun closeWebPortal()
  fun syncItemGrants(handle: Long)

  companion object {
    /** The codec used by PoilinkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PoilinkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PoilinkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setConfig$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val clientIdArg = args[0] as String
            val clientSecretArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setConfig(clientIdArg, clientSecretArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initialize{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.authenticate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appUserIdArg = args[0] as String
            api.authenticate(appUserIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.unauthenticate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unauthenticate()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getRefreshToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRefreshToken{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.setRefreshToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appUserIdArg = args[0] as String
            val refreshTokenArg = args[1] as String
            api.setRefreshToken(appUserIdArg, refreshTokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val missionCodeArg = args[1] as String
            val amountArg = args[2] as Long
            val modeArg = args[3] as Long
            val wrapped: List<Any?> = try {
              api.progressMission(handleArg, missionCodeArg, amountArg, modeArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.progressMissionImmediate$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val missionCodeArg = args[0] as String
            val amountArg = args[1] as Long
            val modeArg = args[2] as Long
            val idempotencyKeyArg = args[3] as String?
            api.progressMissionImmediate(missionCodeArg, amountArg, modeArg, idempotencyKeyArg) { result: Result<List<MissionDataMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.getMissionList$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filterArg = args[0] as MissionListFilterMsg?
            api.getMissionList(filterArg) { result: Result<List<MissionDataMsg>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.showWebPortal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as WebPortalOptionsMsg
            val wrapped: List<Any?> = try {
              api.showWebPortal(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.preloadWebPortal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as WebPortalOptionsMsg
            val wrapped: List<Any?> = try {
              api.preloadWebPortal(optionsArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.closeWebPortal$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.closeWebPortal()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.poilink_sdk.PoilinkHostApi.syncItemGrants$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val handleArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.syncItemGrants(handleArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class PoilinkEventApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by PoilinkEventApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  fun onWebPortalShown(handleArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalShown$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onWebPortalClose(handleArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalClose$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onWebPortalError(handleArg: Long, errorCodeArg: Long, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onWebPortalError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorCodeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onMissionChallenge(handleArg: Long, missionIdArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onMissionChallenge$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, missionIdArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onRewardReceive(handleArg: Long, grantIdArg: String, itemCodeArg: String, quantityArg: Long, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onRewardReceive$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, grantIdArg, itemCodeArg, quantityArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onProgressMissionError(handleArg: Long, errorCodeArg: Long, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onProgressMissionError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorCodeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onGrantsPage(handleArg: Long, grantsArg: List<PendingItemGrantMsg>, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onGrantsPage$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, grantsArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncComplete(handleArg: Long, resultArg: SyncItemGrantsResultMsg, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncComplete$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, resultArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onSyncError(handleArg: Long, errorCodeArg: Long, messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.poilink_sdk.PoilinkEventApi.onSyncError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(handleArg, errorCodeArg, messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
